In [1]:
import sys
import numpy as np 
import pygame
import math 

ROW = 6
COLUMN = 7
SQUARESIZE = 100
RADIUS = int(SQUARESIZE/2 - 5)
BLUE = (0, 0, 225) 
BLACK = (0, 0, 0) 
RED = (255, 0, 0)
YELLOW = (255, 255, 0) 

pygame 2.6.1 (SDL 2.32.54, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
# Checks to see if we can drop a piece in a given column
def validLocation(board, col): 
    return board[ROW - 1][col] == 0


def placePiece(board, row, col, piece): 
    board[row][col] = piece

def nextRow(board, col): 
    for r in range(ROW):
        if board[r][col] == 0: 
            return r

In [3]:
def winningMove(board, piece):
    # Check horizontal 
    for r in range(ROW):
        for c in range(COLUMN - 3):
            if np.all(board[r, c:c+4] == piece):
                return True

    # Check vertical 
    for c in range(COLUMN):
        for r in range(ROW - 3):
            if np.all(board[r:r+4, c] == piece):
                return True
                
    # Check positive diagonal 
    for r in range(ROW - 3):
        for c in range(COLUMN - 3):
            if all(board[r+i, c+i] == piece for i in range(4)):
                return True

    # Check negative diagonal 
    for r in range(3, ROW):
        for c in range(COLUMN - 3):
            if all(board[r-i, c+i] == piece for i in range(4)):
                return True

    return False

In [4]:
def drawBoard(board): 
    for c in range(COLUMN):
        for r in range(ROW):
            pygame.draw.rect(screen, BLUE, (c*SQUARESIZE, r*SQUARESIZE+SQUARESIZE, SQUARESIZE, SQUARESIZE))
            pygame.draw.circle(screen, BLACK, (int(c*SQUARESIZE+SQUARESIZE/2), int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)), RADIUS)
     
    for c in range(COLUMN):
        for r in range(ROW):      
            if board[r][c] == 1:
                pygame.draw.circle(screen, RED, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
            elif board[r][c] == 2: 
                pygame.draw.circle(screen, YELLOW, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
    pygame.display.update()

def printBoard(board):
    print(np.flip(board, 0))

In [5]:
def basicAI(board, col): 
    if validLocation(board, col):
        row = nextRow(board, col)
        placePiece(board, row, col, 1)

In [6]:
def advAI(board, col): 
    if validLocation(board, col):
        row = nextRow(board, col)
        placePiece(board, row, col, 2)

In [7]:
board = np.zeros((6,7))
printBoard(board)
gameOver = False
running = True
turn = 0 

pygame.init()
width = COLUMN * SQUARESIZE
height = (ROW + 1) * SQUARESIZE
size = (width, height)
screen = pygame.display.set_mode(size)

drawBoard(board)
pygame.display.update()
myfont = pygame.font.SysFont("monospace", 75)

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False 

        if event.type == pygame.MOUSEBUTTONDOWN and not gameOver:
            pygame.draw.rect(screen, BLACK, (0,0, width, SQUARESIZE))
            if turn == 0:
                posx = event.pos[0]
                col = int(math.floor(posx/SQUARESIZE))
                basicAI(board, col)
                if winningMove(board, 1):
                    label = myfont.render("Player 1 wins!!", 1, RED)
                    screen.blit(label, (40,10))
                    gameOver = True
            else:     
                posx = event.pos[0]
                col = int(math.floor(posx/SQUARESIZE))
                advAI(board, col)
                if winningMove(board, 2):
                    label = myfont.render("Player 2 wins!!", 1, YELLOW)
                    screen.blit(label, (40,10))
                    gameOver = True
 
            printBoard(board)
            drawBoard(board)
 
            turn += 1
            turn = turn % 2
 
            if gameOver:
                pygame.display.update()

    pygame.display.update()

pygame.quit()

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 2. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 2. 2. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [0. 2. 2. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [2. 2. 2.

## Minimax & Alpha Beta Pruning Baseline

In [ ]:
## Sam brainstorming

# Helper functions before minimax implementation
def get_valid_locations(board):
    return [col for col in range(COLUMN) if validLocation(board, col)]

def simulate_move(board, col, piece):
    # Make a copy
    temp_board = board.copy()

    # Find where this piece will land in the column
    row = nextRow(temp_board, col)

    # Place the piece
    placePiece(temp_board, row, col, piece)

    # Return the new board state
    return temp_board

def is_terminal_node(board):
    return winningMove(board, 1) or winningMove(board, 2) or len(get_valid_locations(board)) == 0

def evaluate(board):
    # AI wins
    if winningMove(board, 1):
        return 1000000

    # Opponent wins
    if winningMove(board, 2):
        return -1000000

    # Otherwise, neutral for now
    return 0

def minimax(board, depth, maximizingPlayer):
    # BASE CASE
    if depth == 0 or is_terminal_node(board):
        return evaluate(board)

# Pseudocode implementation, needs to be finished by sam
function minimax(board, depth, isMaximizingPlayer):
   # First, see if the game is over
   if game is won:
       return +10 if computer wins, -10 if human wins
   if game is tied:
       return 0

   # If it's the computer's turn (maximizing)
   if isMaximizingPlayer:
       bestScore = -infinity
       for each empty spot on board:
           make the move
           score = minimax(board, depth + 1, false)
           undo the move
           bestScore = max(score, bestScore)
       return bestScore

   # If it's the human's turn (minimizing)
   else:
       bestScore = +infinity
       for each empty spot on board:
           make the move
           score = minimax(board, depth + 1, true)
           undo the move
           bestScore = min(score, bestScore)
       return bestScore

SyntaxError: invalid syntax (1835018416.py, line 40)